defaults: &defaults
  host: localhost
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019

development:
  <<: *defaults
  database: logbook_development

test:
  <<: *defaults
  database: logbookI_test

# set these environment variables on your prod server
production:
  <<: *defaults
  #host: <%= ENV['MONGOID_HOST'] %>
  port: 27017 #<%= ENV['MONGOID_PORT'] %>
  #username: aot_mongodb #<%= ENV['MONGOID_USERNAME'] %>
  #password: f96REh #<%= ENV['MONGOID_PASSWORD'] %>
  database: aot_survey_production #<%= ENV['MONGOID_DATABASE'] %>